// Devils Inc Studios
// Copyright DEVILS INC. STUDIOS LIMITED 2015
//
// TODO: Include a description of the file here.
//

namespace DI.Core.GameState
{
	public enum DI_GameStateEvent
	{
		ON_ENTER_CINEMA,
		ON_ENTER_CUT_SCENE,
		ON_ENTER_DIALOG,
		ON_ENTER_LOADING,
		ON_ENTER_LOBBY,
		ON_ENTER_MENU,
		ON_ENTER_PAUSED,
		ON_ENTER_PLAYING,
		ON_ENTER_PLAYING_NO_CONTROL,
		ON_ENTER_UNKNOWN,
		ON_EXIT_CINEMA,
		ON_EXIT_CUT_SCENE,
		ON_EXIT_DIALOG,
		ON_EXIT_LOADING,
		ON_EXIT_LOBBY,
		ON_EXIT_MENU,
		ON_EXIT_PAUSED,
		ON_EXIT_PLAYING,
		ON_EXIT_PLAYING_NO_CONTROL,
		ON_EXIT_UNKNOWN,
	}
}